# Generated by Django 6.0.1 on 2026-04-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
