# Generated by Django 6.0.1 on 2026-04-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='can_send_notifications',
            new_name='can_receive_notifications',
        ),
    ]
