# Generated by Django 6.0.1 on 2026-04-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreference_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='workspace_invites',
            new_name='allows_workspace_invites',
        ),
        migrations.RenameField(
            model_name='userpreference',
            old_name='send_notifications',
            new_name='can_send_notifications',
        ),
    ]
