# Generated by Django 6.0.1 on 2026-03-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preference',
            new_name='UserPreference',
        ),
    ]
