# Generated by Django 6.0.1 on 2026-04-07 08:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_workspace_invites_userpreference_allows_workspace_invites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True, validators=[accounts.models.CustomUser.username_validator]),
        ),
    ]
