# Generated by Django 6.0.1 on 2026-04-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.workspaceuser'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task'),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='workspace_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspaceuser'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('group', 'position'), name='unique_task_position'),
        ),
    ]
