# Generated by Django 6.0.1 on 2026-04-18 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
        ('workspace', '0002_alter_workspacelog_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspaceuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='task.task')),
            ],
        ),
    ]
