# Generated by Django 6.0.1 on 2026-03-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskcomment_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
    ]
