# Generated by Django 6.0.1 on 2026-03-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_parent'),
        ('workspace', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.workspaceuser'),
        ),
    ]
