# Generated by Django 6.0.1 on 2026-04-18 15:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='aaaaafile',
            field=cloudinary.models.CloudinaryField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.BooleanField(default=True),
        ),
    ]
