# Generated by Django 6.0.1 on 2026-04-18 15:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskattachment_aaaaafile_alter_taskattachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskattachment',
            name='aaaaafile',
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
