# Generated by Django 6.0.1 on 2026-04-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task.task'),
        ),
    ]
