# Generated by Django 6.0.1 on 2026-03-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskcomment_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskreminder',
            options={},
        ),
        migrations.RenameField(
            model_name='taskreminder',
            old_name='made_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='taskreminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.DeleteModel(
            name='TaskReminderReceiver',
        ),
    ]
