# Generated by Django 6.0.1 on 2026-04-24 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_taskattachment_aaaaafile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='task.task'),
        ),
    ]
