# Generated by Django 6.0.1 on 2026-03-30 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_taskreminder_options_and_more'),
        ('workspace', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreminder',
            name='user',
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='workspace_user',
            field=models.ForeignKey(default='915bdf96-48dc-4fd3-8369-a92c0159f852', on_delete=django.db.models.deletion.CASCADE, to='workspace.workspaceuser'),
            preserve_default=False,
        ),
    ]
