# Generated by Django 6.0.1 on 2026-03-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_taskreminder_user_taskreminder_workspace_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
