# Generated by Django 6.0.1 on 2026-04-17 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceInviteCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invite_code', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspacePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_roles', models.CharField(choices=[('disabled', 'Disabled'), ('simple', 'Simple'), ('complex', 'Complex')], default='disabled', max_length=20)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('can_edit_workspace_name', models.BooleanField()),
                ('can_edit_workspace_preference', models.BooleanField()),
                ('can_edit_workspace_invite_codes', models.BooleanField()),
                ('can_add_workspace_users', models.BooleanField()),
                ('can_assign_roles_to_workspace_users', models.BooleanField()),
                ('can_remove_workspace_users', models.BooleanField()),
                ('can_edit_workspace_roles', models.BooleanField()),
                ('can_edit_projects', models.BooleanField()),
                ('can_edit_groups', models.BooleanField()),
                ('can_edit_tasks', models.BooleanField()),
                ('can_edit_task_attachments', models.BooleanField()),
                ('can_add_task_comments', models.BooleanField()),
                ('can_edit_task_deadline', models.BooleanField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='workspace.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='default_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='workspace.workspacerole'),
        ),
        migrations.CreateModel(
            name='WorkspaceUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workspace.workspacerole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_user', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=10)),
                ('changes', models.JSONField(default=dict)),
                ('object_id', models.UUIDField(null=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label__in': ['project', 'group', 'task']}, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
                ('workspace_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.workspaceuser')),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='workspace.workspaceuser'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(through='workspace.WorkspaceUser', through_fields=('workspace', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='workspacerole',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_role'),
        ),
        migrations.AddConstraint(
            model_name='workspaceuser',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_user'),
        ),
    ]
