# Generated by Django 6.0.1 on 2026-03-21 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        ('workspace_role', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='default_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='workspace_role.workspacerole'),
        ),
        migrations.AddField(
            model_name='workspaceinvitecode',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='workspacepreference',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='workspaceuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workspace_role.workspacerole'),
        ),
        migrations.AddField(
            model_name='workspaceuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceuser',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_user', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='workspace.workspaceuser'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(through='workspace.WorkspaceUser', through_fields=('workspace', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='workspaceuser',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_user'),
        ),
    ]
