# Generated by Django 6.0.1 on 2026-04-18 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_workspacelog_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvitecode',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='workspace.workspace'),
        ),
        migrations.AlterField(
            model_name='workspacepreference',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='workspace.workspace'),
        ),
    ]
