# Generated by Django 6.0.1 on 2026-04-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_workspacepreference_custom_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacepreference',
            name='custom_roles',
            field=models.CharField(choices=[('deactivated', 'Deactivated'), ('simple', 'Simple')], default='deactivated', max_length=20),
        ),
    ]
