# Generated by Django 6.0.1 on 2026-04-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_workspaceinvitecode_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacerole',
            name='can_assign_tasks_to_users',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
