# Generated by Django 6.0.1 on 2026-04-24 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_workspacerole_can_assign_tasks_to_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacerole',
            name='can_edit_workspace_preference',
        ),
        migrations.DeleteModel(
            name='WorkspacePreference',
        ),
    ]
