# Generated by Django 6.0.1 on 2026-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_alter_workspacepreference_custom_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacepreference',
            name='custom_roles',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('simple', 'Simple'), ('complex', 'Complex')], default='disabled', max_length=20),
        ),
    ]
