# Generated by Django 6.0.1 on 2026-04-02 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('can_edit_workspace_name', models.BooleanField()),
                ('can_edit_workspace_preference', models.BooleanField()),
                ('can_add_users', models.BooleanField()),
                ('can_assign_roles_to_users', models.BooleanField()),
                ('can_remove_users', models.BooleanField()),
                ('can_edit_roles', models.BooleanField()),
                ('can_edit_invite_codes', models.BooleanField()),
                ('can_edit_projects', models.BooleanField()),
                ('can_edit_groups', models.BooleanField()),
                ('can_edit_tasks', models.BooleanField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='workspace.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_role')],
            },
        ),
    ]
