# Generated by Django 6.0.1 on 2026-04-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacerole',
            name='can_add_comments',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspacerole',
            name='can_edit_task_deadline',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
