# Generated by Django 6.0.1 on 2026-04-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_role', '0002_workspacerole_can_add_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacerole',
            old_name='can_add_comments',
            new_name='can_add_task_comments',
        ),
        migrations.RenameField(
            model_name='workspacerole',
            old_name='can_add_users',
            new_name='can_add_workspace_users',
        ),
        migrations.RenameField(
            model_name='workspacerole',
            old_name='can_assign_roles_to_users',
            new_name='can_assign_roles_to_workspace_users',
        ),
        migrations.RenameField(
            model_name='workspacerole',
            old_name='can_edit_invite_codes',
            new_name='can_edit_workspace_invite_codes',
        ),
        migrations.RenameField(
            model_name='workspacerole',
            old_name='can_edit_roles',
            new_name='can_edit_workspace_roles',
        ),
        migrations.RenameField(
            model_name='workspacerole',
            old_name='can_remove_users',
            new_name='can_remove_workspace_users',
        ),
    ]
