# Generated by Django 6.0.1 on 2026-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_role', '0003_rename_can_add_comments_workspacerole_can_add_task_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacerole',
            name='can_edit_task_attachments',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
